# -*- coding: utf-8 -*-
"""Teens login Facebook.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G3isSSnsU3E1wUNojvVTcOtfEUdiEZF-
"""

import numpy as np
import pandas as pd
teens=pd.read_csv("/content/snsdata.csv")
print(teens.shape)

print(teens.dtypes)

teens['gradyear']=teens['gradyear'].astype('str')

print(teens.describe(include='all'))

print(teens.isnull().sum().head())

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
teens_z=sc.fit_transform(teens.iloc[:,4:])

print(type(teens_z))

print(pd.DataFrame(teens_z[:,30:33]).describe())

from sklearn.cluster import KMeans
mdl=KMeans(n_clusters=5,init='random')

pre=dir(mdl)
print(pre[51:56])

mdl.fit(teens_z)
post=dir(mdl)
print(post[51:56])

print(list(set(post)-set(pre)))

import pickle
filename='/content/kmeans.sav'
res=pickle.load(open(filename,'rb'))

print(res.labels_.shape)

print(pd.Series(res.labels_).value_counts())

print(res.labels_[:10])

print(res.cluster_centers_.shape)

cen=pd.DataFrame(res.cluster_centers_,index=range(5),columns=teens.iloc[:,4:].columns)
print(cen)

ax=cen.T.plot()
ax.set_xticks(list(range(36)))
ax.set_xticklabels(list(cen.T.index),rotation=90)
fig=ax.get_figure()
fig.tight_layout()